### ISSUE TITLE
Map unravelling can lead to maps of varying dimensions, causing data_hough_detect to crash

### ISSUE THREAD

**Issue by aringlis** [sunpy/eitwave#23]
I came across an issue this evening where after reading in a set of images (all 1024x1024), the map unravelling phase sometimes returned new maps which varied in dimensions. This causes a crash in data_hough_detect.py. The following code demonstrates how I arrived at this problem.

```
In [32]: filelist = eitwaveutils.loaddata("/Users/ainglis/physics/eitwave_data/20110601_02_04/",
                                 '.jp2')

In [33]: maps = eitwaveutils.accumulate(filelist[0:20], accum=1, super=4, verbose=True)

In [34]: params = {                                                     
          "epi_lat": 50., #degrees, HG latitude of wave epicenter
          "epi_lon": 50., #degrees, HG longitude of wave epicenter
          #HG grid, probably would only want to change the bin sizes
          "lat_min": -90.,
          "lat_max": 90.,
          "lat_bin": 0.2,
          "lon_min": -180.,
          "lon_max": 180.,
          "lon_bin": 5.,
          #    #HPC grid, probably would only want to change the bin sizes
          "hpcx_min": -1025.,
          "hpcx_max": 1023.,
          "hpcx_bin": 2.,
          "hpcy_min": -1025.,
          "hpcy_max": 1023.,
          "hpcy_bin": 2.,
          "hglt_obs": 0,
          "rotation": 360./(27.*86400.), #degrees/s, rigid solar rotation
          }

In [35]: new_maps = eitwaveutils.map_unravel(maps, params, verbose=True) 
Unraveling map 1 of 20 
Unraveling map 2 of 20  
Unraveling map 3 of 20 
Unraveling map 4 of 20 
Unraveling map 5 of 20 
Unraveling map 6 of 20 
Unraveling map 7 of 20 
Unraveling map 8 of 20 
Unraveling map 9 of 20 
Unraveling map 10 of 20 
Unraveling map 11 of 20 
Unraveling map 12 of 20 
Unraveling map 13 of 20 
Unraveling map 14 of 20 
Unraveling map 15 of 20 
Unraveling map 16 of 20 
Unraveling map 17 of 20 
Unraveling map 18 of 20 
Unraveling map 19 of 20 
Unraveling map 20 of 20 

In [36]: for i in range(0,len(new_maps)):
print new_maps[i].shape
....:     
(777, 72)
(777, 72)
(777, 72)
(777, 72)
(777, 72)
(777, 72)
(777, 72)
(777, 72)
(777, 72)
(777, 72)
(777, 72)
(777, 72)
(777, 72)
(778, 72)
(778, 72)
(778, 72)
(778, 72)
(778, 72)
(778, 72)
(778, 72)

In [37]: diffs=eitwaveutils.map_diff(new_maps)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-37-bbf1f9bd8830> in <module>()
----> 1 diffs=eitwaveutils.map_diff(new_maps)

/Users/ainglis/python/eitwave/eitwaveutils.pyc in map_diff(maps)
     76     for i in range(0,len(maps)-1):
     77         # take the difference
---> 78         diffmap = (maps[i+1] - maps[i])
     79         # keep
     80         diffs.append(diffmap)

/Users/ainglis/python/sunpy/sunpy/map/map.pyc in __sub__(self, other)
    331             other = other.astype(to_signed(other.dtype))
    332 
--> 333         result = np.ndarray.__sub__(self, other)
    334 
    335         def norm():

ValueError: operands could not be broadcast together with shapes (778,72) (777,72)
```

Sometimes the dimensions of new_map are (777,72) but sometimes (778,72). This difference in dimensions causes a crash in the eitwaveutils.diff_map function, which assumes all the maps have the same dimensions. I imagine there would be similar problems further along the data_hough_detect chain.

I'm not sure exactly what circumstances cause this, but I came across it for the first time when I changed epi_lat and epi_long in the params dictionary. I had initially thought it might only happen for lat/long values close to the Sun center, but a few quick tests suggested otherwise.

In any case, it's an issue - I suspect there are several places in the code where it's assumed that the maps all have identical dimensions.

**Comment by ayshih** [comment]
I'm 99% sure that the changing sizes are due to the (rigid) solar rotation that can be specified in the simulation parameters.  I recommend setting "rotation" to zero.

The rotation method util.map_hpc_to_hg_rotate() is written to dynamically create the "smallest" heliographic grid for the transformed maps, but the added wrinkle of non-zero solar rotation will mean that the "smallest" range of latitude (in this case, but it could be longitude in others) could change between frames.  The magnitude of this effect will depend on the settings of epi_lat and epi_lon.

Honestly, because Sunpy does not have coordinate-aware map subtraction yet, util.map_hpc_to_hg_rotate() should not be written that way in the first place (damn Steve!), and instead use user-supplied bounds.  Here, even if non-zero solar rotation wasn't at the level of actually changing the dimensions of the maps, the data coordinates could still change slightly, and the difference maps would be subtly wrong.

**Comment by wafels** [comment]
Could we fudge it in the meantime by doing a resampling of the 778,72 data
down to the 777,72 data?

**Comment by aringlis** [comment]
I did a bit more testing to try and diagnose the problem...

I tried turning off the rotation by setting rotation within params to zero. Unfortunately this didn't resolve the problem. A bit more digging revealed that the value of y-center in unravelled maps is changing between frames, even when the input maps all have identical coordinates. 

Below I attempt to attach a plot illustrating this behaviour (if I can figure out Github markup):

![image](http://dl.dropbox.com/u/59101674/eitwave_dimension_issue.png)

In this image example, the original map centers were all (0,0) and the image sizes were (1024,1024). From this plot it seems like after unravelling procedure, the y center (in degrees) is varying slightly between frames, and that this variation is enough in some frames to result in different unravelled image dimensions (the changes in x seem to be negligible).

I tested this on both JPEG2000 data files and on some AIA fits files, and found the same behaviour in each case.

**Comment by ayshih** [comment]
Sorry, I was definitely wrong about the "rotation" parameter (I did say "99%"...).  It's currently only used for making simulated data, not in the unraveling, so it couldn't possibly be related to what you are seeing.

The change in y center is due to the transformation thinking that there are frame-to-frame differences in the range of possible latitudes.  My only guess at this point is that this must result from the changing position of SDO from frame-to-frame.  Can you check how the following properties vary over the course of your map frames?

```
map.heliographic_latitude
map.carrington_longitude
```

As for Jack's suggestion, yes, you could fudge it in the meantime by resampling the maps to the same shape.  Alternatively, you could submap.  Both approaches would result in slightly inaccurate difference maps.

**Comment by aringlis** [comment]
The heliographic latitude and carrington longitude of the original maps seems to vary linearly. Here's a plot:

![image](http://dl.dropbox.com/u/59101674/helio_lat_carrington_long.png)

One other (semi-related) thing I noticed was that the dimensions of the unraveled maps varies by rather a lot, depending on the choice of epi_lat and epi_lon. In the example images I've been using in this thread, if I choose lat/lon as (10,10) the unraveled dimensions are around (520,72), while if I choose lat/lon as (50,50) the unraveled dimensions are around (777,72)! I'm still a little confused by the HG transform, so I'm just going to ask - does that make sense?

Back to the topic: I'll try and implement a 'fudge' solution for now, following one of Jack's suggestions, until we can deal with the problem for the longer term. I'm on travel back to DC on Monday - I'll be in the office Tuesday.

**Comment by ayshih** [comment]
It's not immediately obvious to me that the magnitude of the "heliographic latitude" and "carrington longitude" are sufficient to cause what you are seeing, but I can't think of any other candidates.

Yes, the dimensions of the unraveled maps will vary quite a bit depending on the location of the epicenter.  If you set the epicenter at (0,0), then your HG' map would not be able to see anything below 90 degrees in latitude (barring any correction for "heliographic latitude").  Thus, at a latitude binning of 0.2 degrees, that means there could be as few as 450 latitude bins.  At the other extreme, an epicenter at (90,*) would result in an HG' map with all latitudes (180 degrees), and the maximum number of latitude bins would be 900.  Note that in this case, and other high-latitude epicenters, the HG' map will not contain all 360 degrees of longitude, so it is possible to have maps that have less than 72 longitude bins.

**Comment by aringlis** [comment]
The fix I implemented is not robust: 

Currently the dimensions check is performed by eitwaveutils.check_dims. This function reads in a list of unraveled maps, grabs the dimensions of the first one in the list, and forces all the other maps in the list to those same dimensions if necessary.

The dimension change is performed by map.resample. However, map.resample can only shrink the dimensions of a numpy array, it cannot grow them. See below for an example.

```
 In [10]: new_maps[0].shape[::-1]    
 Out[10]: (72, 472)

 In [11]: tmp=new_maps[0].resample((72,471),method='linear')

 In [12]: tmp.shape[::-1] 
 Out[12]: (72, 471)

 In [13]: tmp=new_maps[0].resample((72,473),method='linear')
 ---------------------------------------------------------------------------
 ValueError                                Traceback (most recent call last)
 <ipython-input-13-9fe650440118> in <module>()
 ----> 1 tmp=new_maps[0].resample((72,473),method='linear')
```
